### ISSUE TITLE
No authorization string

### ISSUE THREAD

**Issue by cbergqvist** [jamiesun/SublimeEvernote#18]
Did Evernote application authorization process change? It isn't giving me an authorization string for me to enter in Sublime.

**Comment by dencold** [comment]
Hi @gymdis, it's a little tricky to get this working.  I have an open pull request to improve the readme, but it looks like @jamiesun hasn't had time to review. In the meantime, you can check out the instructions that I've included on my pull request here:
https://github.com/dencold/SublimeEvernote/blob/3e63f0865556f7e1e335eba8c2c600ede9d26634/Readme.md

It should guide you through the process. Let me know if it helps!
--Dennis

**Comment by cbergqvist** [comment]
Hi @dencold, thanks for helping me so swiftly, got it working now!
Hope he gets time to review it soon.
/ Chris

**Comment by dencold** [comment]
No problem! Glad it all worked out for you.
