### ISSUE TITLE
"Error EDAMUserException" after copying the oauth verifier

### ISSUE THREAD

**Issue by titouanmathis** [jamiesun/SublimeEvernote#19]
Sublime Text prompt this message after copying the oauth verifier and pressing enter:

![capture decran 2013-10-19 a 10 39 55](https://f.cloud.github.com/assets/250145/1365073/a0bf6376-384e-11e3-8534-382df1f349a2.png)

I'm on a Mac OSX 10.8.5 with Sublime Text 2, the application appears on my Evernote account as authorized.

**Comment by leecade** [comment]
I get this error:

```
Error getting notebooks: EDAMSystemException(rateLimitDuration=None, message='authenticationToken', errorCode=8)
```

**Comment by jamiesun** [comment]
error has been corrected
