### ISSUE TITLE
Error on Console - No "Send to Evernote" Command

### ISSUE THREAD

**Issue by nmacosta** [jamiesun/SublimeEvernote#20]
When Trying to install SublimeEvernote on console this errors appear.

Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./sublime_evernote.py", line 12, in <module>
    import oauth2 as oauth
  File "lib/oauth2/**init**.py", line 32, in <module>
    import httplib2
  File "lib/httplib2/**init**.py", line 909, in <module>
    class HTTPSConnectionWithTimeout(httplib.HTTPSConnection):
AttributeError: 'module' object has no attribute 'HTTPSConnection'
found 16 files for base name Default.sublime-keymap

**Comment by bstoutenburgh** [comment]
Linux?  I'm seeing similar issues which all go back to ssl being removed from the Sublime Text 2 builds which leaves httplib without https support.

https://www.sublimetext.com/forum/viewtopic.php?f=6&t=2606
http://www.sublimetext.com/forum/viewtopic.php?f=6&t=5633

Other package developers have had to package ssl.so themselves to provide support or use workarounds like curl.

Even putting an ssl-enabled version of httplib.py in the repository though, I have no idea how to get SublimeEvernote's httplib2 to use it over the one already loaded from sublime's own lib/python26.zip.

**Comment by bstoutenburgh** [comment]
I ended up playing with some jenky things and with some inspiration from sublime text's own sublime_plugin.py got something to work on my system.  It should be cleaned up by someone that knows Python better but give this fork a shot:  [maristgeek/SublimeEvernote](https://github.com/maristgeek/SublimeEvernote)

``` python
# Force loading of SSL-enabled httplib
import imp
import os
import sublime
lib_folder = os.path.join(sublime.packages_path(), 'SublimeEvernote', 'lib')
m_info = imp.find_module('httplib', [lib_folder])
m = imp.load_module('httplib', *m_info)
import httplib
print httplib.__file__
```

**Comment by bstoutenburgh** [comment]
Oh, guess I should note that I used pythonbrew to compile an SSL-enabled python 2.6 and copied httplib.py from there to SublimeEvernote/lib.
