### ISSUE TITLE
I don't see Send to evernote in the command palette

### ISSUE THREAD

**Issue by cedricmessiant** [jamiesun/SublimeEvernote#27]
After installation (SublimeText 2.0.2 (build 2221)), I only have SublimeEvernote Settings in the command palette. I don't see any other commands.

**Comment by bstoutenburgh** [comment]
Can you disable the package and watch the console as you enable it again?  Trying to see if you have the problem I'm seeing which is in issue #20.

**Comment by cedricmessiant** [comment]
Thank you. Indeed, I have the same Traceback : 

```
Reloading plugin /home/cedricmessiant/.config/sublime-text-2/Packages/SublimeEvernote/html.py
Reloading plugin /home/cedricmessiant/.config/sublime-text-2/Packages/SublimeEvernote/sublime_evernote.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./sublime_evernote.py", line 12, in <module>
    import oauth2 as oauth
  File "lib/oauth2/__init__.py", line 32, in <module>
    import httplib2
  File "lib/httplib2/__init__.py", line 909, in <module>
    class HTTPSConnectionWithTimeout(httplib.HTTPSConnection):
AttributeError: 'module' object has no attribute 'HTTPSConnection'
```

**Comment by ghost** [comment]
This should probably get closed as a duplicate then.  That testing I did in #20 should have some conditionals to only do that dirtiness for Linux.

It's bad form for me to say this but the [ST3 fork](https://sublime.wbond.net/packages/Evernote) of this project works in Linux and is pretty slick.

**Comment by cedricmessiant** [comment]
Ok, I close the issue. Thanks again
