### ISSUE TITLE
Getting 'error: error:bad numeric conversion: positive overflow' on authentication

### ISSUE THREAD

**Issue by leisinmr** [jamiesun/SublimeEvernote#3]
I entered my username and password the first time and I got the following error:
error: error:bad numeric conversion: positive overflow

**Comment by linvald** [comment]
I got the same error on Mac OSX

**Comment by du-song** [comment]
same here, OSX 10.8, ST2 build 2218

**Comment by reklis** [comment]
SAME

**Comment by jamiesun** [comment]
This may be caused by a time zone,I being analyzed

**Comment by jamiesun** [comment]
the mac osx may have long integer overflow problem,I use Decimal to replace the the long integer,Should be able  fix this bug,Please upgrade plug-ins
