### ISSUE TITLE
Doesn't show up in Package Control

### ISSUE THREAD

**Issue by exceptionraiser** [jamiesun/SublimeEvernote#4]
SublimeEvernote doesn't show up in Package Control even after I add the `http://github.com/jamiesun/SublimeEvernote` repo.

Thoughts?

**Comment by jamiesun** [comment]
SublimeEvernote  been released, and does not need to add the channel

Command Palette > Package Control: Install Package > SublimeEvernote

Better for you to perform the Command Palette> Package Control: Upgrade

**Comment by exceptionraiser** [comment]
Still no dice. I've added it as a repo as well. Thanks for the help!
