### ISSUE TITLE
ST2 console doesn't work anymore after installing SublimeEvernote

### ISSUE THREAD

**Issue by bizoo** [jamiesun/SublimeEvernote#6]
Hi,

Thanks for your works, it's a nice plugin.

I have only an (severe) issue with it, after installing SublimeEvernote, I couldn't use ST2 console anymore. When I type a command, nothing happen as my text didn't go it's way to the Python interpreter.
Maybe something related to stdin/stdout ?

startup, version: 2219 windows x64 channel: nightly

**Comment by jamiesun** [comment]
I think it might be because of the following code:

```
reload (sys)
```

I have deleted it

it fixed on my computer,test result

```
>>> print 1
1
```

please upgrade,and reboot st2

**Comment by bizoo** [comment]
Works now for me too.
Thanks.
