### ISSUE TITLE
Can we send HTML documents

### ISSUE THREAD

**Issue by vytch** [jamiesun/SublimeEvernote#8]
Hi I have read in the documentation and apparently we are allowed to use tags such as h1, h2 and the like.

I tried to create a document with those basic tags however Evernote does not seem to keep them.
Here is what I have:

```
&lt;/h1&gt;
```

Is it something that can be fixed at the sublime plugin level?

Thanks

**Comment by oparrish** [comment]
I have a fork that supports Markdown.  It will be processed into HTML when it is sent to Evernote.  https://github.com/oparrish/SublimeEvernote
