### ISSUE TITLE
ConsumerKey error

### ISSUE THREAD

**Issue by luispapopepo** [jamiesun/SublimeEvernote#9]
Hello,
I am getting this error when i try to sent the note to evernote.

error:EDAMUserException(errorCode=8, parameter='consumerKey')

¿Know why?

Regards.

**Comment by writeclick** [comment]
I'm getting the same error. Thanks.

**Comment by writeclick** [comment]
It would appear that this app needs to be updated to use oAuth now. So I guess that's the reason for the error.

**Comment by seagoj** [comment]
Just adding that I'm also having the issue and I'm really hoping this gets resolved. It seems like a great idea.

**Comment by oparrish** [comment]
I have a fork that implements OAuth (and adds Markdown support)  https://github.com/oparrish/SublimeEvernote

**Comment by seagoj** [comment]
Your fork works perfectly. Thanks for pointing it out!

Though, you might want to change the github URL in the README to your repo if it is not going to get merged back in anytime soon.

**Comment by oparrish** [comment]
@seagoj Thanks for pointing that out.  Did you install via Package Control by adding the repository?  Or did you just clone the repo?

**Comment by seagoj** [comment]
I just cloned the repo.

Jeremy Seago
1224 Russell Blvd
St. Louis, MO 63104
314.467.0643

**Comment by shmup** [comment]
Any clue why authorizing on Evernote sends me to http://127.0.0.1/?oauth_token_******** ?

**Comment by oparrish** [comment]
Evernote doesn't support an OAuth desktop flow so, they require a callback URL to redirect to after a user authorizes.  The verifier parameter from that URL is what you need to paste in Sublime Text.

It's not very user friendly but, it works.  

I'd like to try spinning up a temporary HTTP server to deal with the call back to make it a little easier for people to authorize.

**Comment by shmup** [comment]
I'm actually not seeing an additional parameter in the URL, so I must be doing something wrong.

I start with:
https://www.evernote.com/OAuth.action?oauth_token=oparrish-12345

and end with:
http://127.0.0.1/?oauth_token=oparrish-12345

edit: just realized you may have just meant I need to paste 12345 into Sublime after authorizing on Evernote, which I tried.

**Comment by oparrish** [comment]
The URL that you originial visit to Authorize SublimeEvernote should look much longer than that

**Comment by shmup** [comment]
12345 stood as an example, it is much longer. Much much longer, hah.

**Comment by oparrish** [comment]
After you click Authorize - the URL in your browser should have at the end &verifier=SOMETHING  - Do you not see that?

**Comment by shmup** [comment]
I really hope someone is as derpy as me so these comments are actually helpful.

Yes, I see it now. Thank you.

**Comment by oparrish** [comment]
Like I said - not very user friendly.  Hopefully I can find time to make it better

**Comment by karldanninger** [comment]
@shmup I was derpy enough.  Thank you!

Thanks @oparrish works like a charm.

**Comment by 7Moses** [comment]
Derpy is probably the right word. Can someone post the complete url shmup refers to above when s/he writes, "I start with:"
-I have that authorization issue and I am getting nowhere fast with the above directions.

Thanks

**Comment by sf-billops** [comment]
Once you authorize, you should see a long URL that looks like this:
http://127.0.0.1/?oauth_token=oparrish-4096.13CCA52210F.687474703A2F2F3132372E302E302E31.313Dxxxxxxxxxxxx3344638E&oauth_verifier=36xxxxx42E8111732C3C5B13054031608.

I pasted in everything after oath_verifier=  and it seems to have worked.

**Comment by 7Moses** [comment]
Thanks.

**Comment by mildfuzz** [comment]
Is this pull request likely to get accepted? I'd rather stick with the official repo if I can, but not if it is broken. No response from maintainer to this thread makes me think it's been abandoned?

**Comment by dencold** [comment]
I just added pull request #17 to try and help clear up the confusion on oauth verification on the README.  I think many people have similar experiences to @shmup.
